import os
from pathlib import Path

# Base directory: .../ERC-4337/erc4337-security-test/batch_test
BASE_DIR = Path(__file__).resolve().parent

# Test Root directory: .../ERC-4337/erc4337-security-test
TEST_ROOT = BASE_DIR.parent

# Path to deployments.json (Generated by deploy_contracts.py in erc4337-security-test/data)
# Full path: .../ERC-4337/erc4337-security-test/data/deployments.json
DEPLOYMENTS_PATH = TEST_ROOT / 'data' / 'deployments.json'

# Path to save reports
REPORTS_DIR = TEST_ROOT / 'data' / 'reports'

# Ensure reports directory exists
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# Hardhat RPC URL
RPC_URL = "http://127.0.0.1:8545"
