# test_runner.py
from __future__ import annotations

from pathlib import Path

import streamlit as st

from core.config_store import ConfigStore
from core.history import append_run_history, ensure_run_history, filter_run_history
from core.manifest import RunManifest
from core.tests import TestService


def _apply_test_runner_style() -> None:
    st.markdown(
        """
        <style>
        .stButton > button {
            width: 100%;
        }
        .result-card {
            padding: 0.25rem 0 0.25rem 0;
        }
        .stTextArea textarea {
            white-space: pre-wrap !important;
        }
        div[data-testid="stCodeBlock"] pre {
            white-space: pre-wrap !important;
            word-break: break-word !important;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def _render_result_block(
    title: str,
    stdout: str,
    stderr: str = "",
    command: list[str] | None = None,
    manifest_path: str | None = None,
    returncode: int | None = None,
    key_base: str | None = None,
) -> None:
    with st.container(border=True):
        st.markdown(f"### {title}")
        if returncode is not None:
            if returncode == 0:
                st.success("Execution Successful")
            else:
                st.error(f"Execution Failed rc={returncode}")

        if command or manifest_path:
            with st.expander("View Technical Details", expanded=False):
                if command:
                    st.caption("Command")
                    st.code(" ".join(command), language="bash")
                if manifest_path:
                    st.caption(f"Manifest: {manifest_path}")

        output_tabs = st.tabs(["stdout", "stderr"])
        stdout_key = f"{key_base or title}_stdout"
        stderr_key = f"{key_base or title}_stderr"
        with output_tabs[0]:
            st.text_area(
                "stdout",
                value=stdout or "(no stdout)",
                height=260,
                disabled=True,
                label_visibility="collapsed",
                key=stdout_key,
            )
        with output_tabs[1]:
            st.text_area(
                "stderr",
                value=stderr or "(no stderr)",
                height=220,
                disabled=True,
                label_visibility="collapsed",
                key=stderr_key,
            )


def _render_test_guide() -> None:
    st.markdown("### Test Instructions")
    st.caption("Preserves original test responsibilities, does not forcibly convert old tests into unified dataset entry points.")

    with st.expander("Why do these tests seem repetitive but are not recommended to merge directly?", expanded=False):
        st.markdown(
            "\n".join(
                [
                    "- These tests all relate to ERC-4337's handleOps, but focus on different levels.",
                    "- Signature Test and High Severity are specialized regression tests, aiming to verify fixed security assumptions, not general sample executors.",
                    "- Batch Test is a baseline batch test, input is from the project's internal AttackVector, not external JSON datasets.",
                    "- AI Dataset validation / on-chain execution is the entry point designed for external attack datasets.",
                    "- Directly converting all old tests to dataset-driven would change the boundary and assertion semantics intended by the original author.",
                ]
            )
        )

    columns = st.columns(2)
    guides = [
        {
            "title": "Batch Test",
            "goal": "Fixed baseline + a few extended samples, quickly see overall block rate and result distribution.",
            "input": "AttackVector generated by the project's internal FixedCaseGenerator / MockGenerator.",
            "dataset": "No. Not an external dataset entry point.",
            "when": "Run when you want to quickly check if local deployment is basically working and reports are produced normally.",
        },
        {
            "title": "Signature Test",
            "goal": "Verify security logic related to signature validation, a specialized regression test.",
            "input": "Fixed PackedUserOperation constructed within the script.",
            "dataset": "No. Not written according to a generic JSON sample protocol.",
            "when": "Run after modifying signature validation, owner, hash, nonce related logic.",
        },
        {
            "title": "High Severity Scenarios",
            "goal": "Verify specific high-risk attack scenarios and attack contract interaction results.",
            "input": "Fixed scripts + pre-deployed attack contracts + specific callData.",
            "dataset": "No. Depends on scenario preconditions, not a general sample executor.",
            "when": "Run after modifying attack contracts, deployment scripts, or key protection logic.",
        },
        {
            "title": "AI Dataset Validation / On-Chain Execution",
            "goal": "Consume external attack datasets, perform structural validation and on-chain sampling execution.",
            "input": "External JSON datasets, e.g., cleaned 1200-entry dataset.",
            "dataset": "Yes. Currently the frontend's only dataset testing entry point.",
            "when": "Run validation first after generating a new dataset, then run on-chain sampling execution.",
        },
    ]

    for index, guide in enumerate(guides):
        with columns[index % 2]:
            with st.container(border=True):
                st.markdown(f"**{guide['title']}**")
                st.write(f"Test Goal: {guide['goal']}")
                st.write(f"Input Source: {guide['input']}")
                st.write(f"Supports External Attack Dataset: {guide['dataset']}")
                st.write(f"When to Use: {guide['when']}")

    st.info(
        "Recommended sequence: 1) Batch to see if baseline is normal 2) Signature / High Severity to see specialized security regression 3) AI Dataset validation & on-chain execution to see if generated dataset is usable."
    )


def _render_history() -> None:
    items = filter_run_history(st.session_state, module="test_runner", limit=50)
    st.markdown("### Test Runner History (Current Session)")
    if not items:
        st.info("No Test Runner records in current session yet.")
        return

    for i, item in enumerate(items):
        rc = item.get("returncode")
        status = "✅" if rc == 0 else "❌"
        title = f"{status} {item.get('timestamp', 'N/A')} | {item.get('action', 'test')} | rc={rc}"
        with st.expander(title, expanded=(i == 0)):
            cmd = item.get("command") or []
            _render_result_block(
                title="History Record Details",
                stdout=item.get("stdout") or "",
                stderr=item.get("stderr") or "",
                command=cmd,
                manifest_path=item.get("manifest_path"),
                returncode=rc,
                key_base=f"history_{i}_{item.get('timestamp', 'na')}",
            )


def _summarize_output(stdout: str, returncode: int | None) -> None:
    lines = [line.strip() for line in (stdout or "").splitlines() if line.strip()]
    summary_lines = [line for line in lines if line.startswith("Summary:") or line.startswith("Validation:") or line.startswith("Loaded dataset:")]
    if returncode == 0:
        if summary_lines:
            for line in summary_lines[-3:]:
                st.success(line)
        else:
            st.success("Execution Completed")
    else:
        if summary_lines:
            for line in summary_lines[-3:]:
                st.warning(line)


def render() -> None:
    _apply_test_runner_style()
    st.subheader("Test Runner")
    root = Path(st.session_state.project_root)
    test_service = TestService(root)
    cfg = ConfigStore(root).load()
    manifest = RunManifest(root)
    ensure_run_history(st.session_state)

    st.info(
        "Frontend currently integrates 5 test paths: Batch, Signature, High Severity, AI Dataset Validation, AI Dataset On-Chain Execution."
    )
    _render_test_guide()

    baseline_tab, regression_tab, dataset_tab = st.tabs(["Baseline Batch", "Specialized Regression", "Dataset Testing"])

    with baseline_tab:
        with st.container(border=True):
            st.markdown("### Batch Test")
            st.caption("Fixed baseline samples + a few extended samples, quickly judge if local deployment and basic protection are normal.")
            batch_count = st.number_input(
                "Batch Random Extension Count",
                min_value=0,
                max_value=1000,
                value=int(cfg.get("batch_count", 8)),
            )
            if st.button("Run Batch Test"):
                res = test_service.run_batch(batch_count)
                path = manifest.record({"module": "test_runner", "type": "batch", "command": res.command, "returncode": res.returncode})
                append_run_history(
                    st.session_state,
                    module="test_runner",
                    action="batch",
                    command=res.command,
                    returncode=res.returncode,
                    stdout=res.stdout,
                    stderr=res.stderr,
                    manifest_path=str(path),
                    max_items=50,
                )
                _render_result_block(
                    title="Batch Test Result",
                    stdout=res.stdout,
                    stderr=res.stderr,
                    command=res.command,
                    manifest_path=str(path),
                    returncode=res.returncode,
                    key_base="batch_result",
                )

    with regression_tab:
        with st.container(border=True):
            st.markdown("### Signature Test")
            st.caption("Fixed signature attack vector regression. Suitable for execution after modifying signature validation, owner, nonce logic.")
            if st.button("Run Signature Test"):
                res = test_service.run_signature()
                path = manifest.record({"module": "test_runner", "type": "signature", "command": res.command, "returncode": res.returncode})
                append_run_history(
                    st.session_state,
                    module="test_runner",
                    action="signature",
                    command=res.command,
                    returncode=res.returncode,
                    stdout=res.stdout,
                    stderr=res.stderr,
                    manifest_path=str(path),
                    max_items=50,
                )
                _summarize_output(res.stdout, res.returncode)
                _render_result_block(
                    title="Signature Test Result",
                    stdout=res.stdout,
                    stderr=res.stderr,
                    command=res.command,
                    manifest_path=str(path),
                    returncode=res.returncode,
                    key_base="signature_result",
                )

        with st.container(border=True):
            st.markdown("### High Severity Scenarios")
            st.caption("First deploy attack contracts, then execute fixed high-risk attack scenarios. Suitable for checking specific exploit paths.")
            if st.button("Run High Severity Scenarios"):
                dres, tres = test_service.run_high_severity()
                path = manifest.record(
                    {
                        "module": "test_runner",
                        "type": "high_severity",
                        "commands": [dres.command, tres.command],
                        "returncodes": [dres.returncode, tres.returncode],
                    }
                )
                combined_stdout = "\n\n".join(
                    [
                        "[deploy_attack.py]",
                        dres.stdout or "(no stdout)",
                        "[test_vulnerability.py]",
                        tres.stdout or "(no stdout)",
                    ]
                )
                combined_stderr = "\n\n".join(
                    [
                        "[deploy_attack.py]",
                        dres.stderr or "",
                        "[test_vulnerability.py]",
                        tres.stderr or "",
                    ]
                ).strip()
                append_run_history(
                    st.session_state,
                    module="test_runner",
                    action="high_severity",
                    command=["python", "scripts/deploy_attack.py", "&&", "python", "tests/test_vulnerability.py"],
                    returncode=max(dres.returncode, tres.returncode),
                    stdout=combined_stdout,
                    stderr=combined_stderr,
                    manifest_path=str(path),
                    max_items=50,
                )
                _summarize_output(combined_stdout, max(dres.returncode, tres.returncode))
                result_tabs = st.tabs(["Deployment Output", "Vulnerability Scenario Output"])
                with result_tabs[0]:
                    _render_result_block(
                        title="deploy_attack.py Result",
                        stdout=dres.stdout,
                        stderr=dres.stderr,
                        command=dres.command,
                        manifest_path=str(path),
                        returncode=dres.returncode,
                        key_base="deploy_attack_result",
                    )
                with result_tabs[1]:
                    _render_result_block(
                        title="test_vulnerability.py Result",
                        stdout=tres.stdout,
                        stderr=tres.stderr,
                        command=tres.command,
                        manifest_path=str(path),
                        returncode=tres.returncode,
                        key_base="vulnerability_result",
                    )

    with dataset_tab:
        with st.container(border=True):
            st.markdown("### AI Dataset Test")
            st.caption("Targeted for external attack datasets. It is recommended to run structural validation first, then on-chain sampling execution.")
            dataset_path = st.text_input(
                "Dataset Path",
                value=cfg.get("ai_clean_dataset_output", "ai-attack-generator/attacks_dataset_1200_clean.json"),
                key="ai_dataset_path_test",
            )

            ai_chain_limit = st.number_input(
                "On-Chain Execution Limit",
                min_value=1,
                max_value=500,
                value=50,
                key="ai_dataset_chain_limit",
            )
            include_legitimate = st.checkbox(
                "Include legitimate samples during on-chain execution",
                value=False,
                key="ai_dataset_chain_include_legitimate",
                help="By default, only execute attack samples with should_be_blocked=true, to avoid legitimate samples polluting results due to local deployment environment mismatches.",
            )
            if st.button("Run AI Dataset Validation"):
                res = test_service.run_ai_dataset_test(dataset_path)
                path = manifest.record({"module": "test_runner", "type": "ai_dataset", "command": res.command, "returncode": res.returncode})
                append_run_history(
                    st.session_state,
                    module="test_runner",
                    action="ai_dataset",
                    command=res.command,
                    returncode=res.returncode,
                    stdout=res.stdout,
                    stderr=res.stderr,
                    manifest_path=str(path),
                    max_items=50,
                )
                _summarize_output(res.stdout, res.returncode)
                _render_result_block(
                    title="AI Dataset Validation Result",
                    stdout=res.stdout,
                    stderr=res.stderr,
                    command=res.command,
                    manifest_path=str(path),
                    returncode=res.returncode,
                    key_base="ai_dataset_validate_result",
                )

            if st.button("Run AI Dataset On-Chain Test"):
                res = test_service.run_ai_dataset_chain(
                    dataset_path=dataset_path,
                    limit=int(ai_chain_limit),
                    include_legitimate=include_legitimate,
                )
                path = manifest.record({"module": "test_runner", "type": "ai_dataset_chain", "command": res.command, "returncode": res.returncode})
                append_run_history(
                    st.session_state,
                    module="test_runner",
                    action="ai_dataset_chain",
                    command=res.command,
                    returncode=res.returncode,
                    stdout=res.stdout,
                    stderr=res.stderr,
                    manifest_path=str(path),
                    max_items=50,
                )
                _summarize_output(res.stdout, res.returncode)
                _render_result_block(
                    title="AI Dataset On-Chain Test Result",
                    stdout=res.stdout,
                    stderr=res.stderr,
                    command=res.command,
                    manifest_path=str(path),
                    returncode=res.returncode,
                    key_base="ai_dataset_chain_result",
                )

    st.divider()
    _render_history()